# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cf8e135350f624ed7b2efc83a61a6ba92ab8dcd57599c3229ef9d145e751fdd855ebe6ef093cc3962c3c97f7c34e7fb893124e6498cc6973a403253da99db3b

test:
  secret_key_base: 2c28bd6c5ba1c5f2408353d4b7412888a197b5586b37d9c2af3dffdd763b1750f0cfc5849411b8e50c9082a6b3cba5240578da240d23a214e4ffd04805e62ec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
